# Use case configuration for Xiaomi POCO X3
# -> /usr/share/alsa/ucm2/conf.d/sm8250/POCO X3.conf

Syntax 3

SectionUseCase."HiFi" {
        File "/Xiaomi/surya/HiFi.conf"
        Comment "HiFi quality Music."
}

SectionUseCase."Voice Call" {
        File "/Xiaomi/surya/VoiceCall.conf"
        Comment "Make a phone call"
}
